# Generated by Django 6.0.1 on 2026-02-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('school_name', models.CharField()),
                ('grade', models.CharField()),
                ('is_solved', models.BooleanField()),
                ('difficulty', models.IntegerField(blank=True)),
                ('file', models.FileField(upload_to='')),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
    ]
