# Generated by Django 6.0.1 on 2026-02-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(default='نوبت1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='writer',
            field=models.CharField(default='حسین'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='راحت'),
        ),
    ]
