# Generated by Django 6.0.6 on 2026-07-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_question_tags_question_writer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="slug",
            field=models.SlugField(default="djangodbmodelsfieldscharfield"),
        ),
    ]
