# Generated by Django 6.0.6 on 2026-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_question_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
