# Generated by Django 6.0.6 on 2026-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_alter_question_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="description",
            field=models.TextField(),
        ),
    ]
