# Generated by Django 6.0.6 on 2026-07-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_alter_question_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="description",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(db_index=True, default="راحت"),
        ),
        migrations.AlterField(
            model_name="question",
            name="grade",
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_solved",
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="school_name",
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="writer",
            field=models.CharField(db_index=True),
        ),
    ]
