# Generated by Django 6.0.6 on 2026-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0007_alter_question_description_alter_question_difficulty_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["grade", "-likes_count"], name="question_grade_likes_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["school_name", "-likes_count"], name="question_school_likes_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty", "-likes_count"], name="question_diff_likes_idx"
            ),
        ),
    ]
