# Generated by Django 6.0.6 on 2026-07-18 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_question_question_grade_likes_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="file",
            field=models.FileField(
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
