# Generated by Django 6.0.1 on 2026-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='joined',
            field=models.DateField(auto_now=True),
        ),
    ]
