# Generated by Django 6.0.1 on 2026-02-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscriber_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField()),
                ('message', models.CharField()),
                ('sent', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
