# Generated by Django 6.0.1 on 2026-02-03 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_alter_subscriber_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='writer_name',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
