# Generated by Django 6.0.6 on 2026-07-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_news_writer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="writer_name",
        ),
    ]
