# Generated by Django 6.0.6 on 2026-07-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_remove_news_writer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
