# Generated by Django 6.0.6 on 2026-07-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_news_id_alter_subscriber_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="message",
            field=models.TextField(),
        ),
    ]
