# Generated by Django 6.0.6 on 2026-07-17 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_news_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="unsubscribe_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
