# Generated by Django 6.0.1 on 2026-02-07 16:55

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_forgotpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='expire_date',
            field=models.DateTimeField(default=user.models.four_hours_from_now),
        ),
    ]
