# Generated by Django 6.0.1 on 2026-02-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='likes_count',
        ),
    ]
