# Generated by Django 6.0.1 on 2026-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userprofile_comments_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
