# Generated by Django 6.0.1 on 2026-02-09 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.CharField(default='دیفالت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.CharField(default=5),
            preserve_default=False,
        ),
    ]
