# Generated by Django 6.0.1 on 2026-02-09 14:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_comment_created_at_comment_message_comment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
            preserve_default=False,
        ),
    ]
