# Generated by Django 6.0.1 on 2026-02-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_comment_book_like_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon',
        ),
    ]
