# Generated by Django 6.0.6 on 2026-07-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_remove_badge_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeleteAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
