# Generated by Django 6.0.6 on 2026-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_deleteaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deleteaccount",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
