# Generated by Django 6.0.6 on 2026-07-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_deleteaccount_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgotpassword",
            name="token",
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="score",
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
