# Generated by Django 6.0.6 on 2026-07-17 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0008_book_book_grade_likes_idx_book_book_school_likes_idx"),
        ("questions", "0008_question_question_grade_likes_idx_and_more"),
        ("user", "0016_alter_forgotpassword_token_alter_userprofile_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["liked_by", "question", "-id"], name="like_user_q_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["liked_by", "book", "-id"], name="like_user_b_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["-score"], name="userprofile_score_idx"),
        ),
    ]
