# Generated by Django 6.0.6 on 2026-07-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
