# Generated by Django 6.0.6 on 2026-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_chat_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_ai", models.BooleanField()),
                ("text", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="chat",
            name="count",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="context",
        ),
        migrations.AddField(
            model_name="chat",
            name="context",
            field=models.ManyToManyField(to="ai.message"),
        ),
    ]
