# Generated by Django 6.0.6 on 2026-07-04 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_message_remove_chat_count_remove_chat_context_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="context",
        ),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context",
                to="ai.chat",
            ),
        ),
    ]
