# Generated by Django 6.0.6 on 2026-07-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_memory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="context",
            field=models.ManyToManyField(to="ai.message"),
        ),
    ]
