# Generated by Django 6.0.6 on 2026-07-17 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_alter_memory_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["user", "-created_date"], name="chat_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["chat", "-id"], name="message_chat_recent_idx"),
        ),
    ]
