from ai.models import Chat, Message , Memory
from django.contrib.auth import get_user_model
import uuid

User = get_user_model()

from ai.models import Chat, Message , Memory
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User as DjangoUser
from django.db.models import QuerySet
import uuid
from typing import Optional, Union, List

User = get_user_model()

def get_all_chats(username: str) -> QuerySet[Chat]:
    """
    Retrieve all chats for a given user, ordered by creation date descending.

    Args:
        username (str): The username of the chat owner.

    Returns:
        QuerySet[Chat]: A queryset of Chat records.

    document by AI
    """
    return Chat.objects.filter(user__username=username).order_by("-created_date")

def create_new_chat(username: str) -> Optional[Chat]:
    """
    Create a new chat session for a user.

    Args:
        username (str): The username of the user.

    Returns:
        Optional[Chat]: The created Chat object, or None if user does not exist.

    document by AI
    """
    try:
        user_instance = User.objects.get(username=username)
        chat_uuid = uuid.uuid4()
        new_chat = Chat.objects.create(user=user_instance, uuid=chat_uuid)
        return new_chat
    except User.DoesNotExist:
        return None

def get_chat_by_uuid(username: str, chat_uuid: Union[uuid.UUID, str]) -> Optional[Chat]:
    """
    Retrieve a specific chat by its UUID and owner's username.

    Args:
        username (str): The username of the chat owner.
        chat_uuid (Union[uuid.UUID, str]): The UUID of the chat.

    Returns:
        Optional[Chat]: The matching Chat instance, or None if not found.

    document by AI
    """
    try:
        return Chat.objects.get(uuid=chat_uuid, user__username=username)
    except:
        return None

def add_to_memory(user: DjangoUser, message: Message) -> None:
    """
    Add a message to the user's AI memory context, keeping up to 20 messages.

    Args:
        user (DjangoUser): The User instance.
        message (Message): The message to add.

    document by AI
    """
    memory , _ = Memory.objects.get_or_create(user=user)
    
    if memory.context.filter(text=message.text).exists():
        return
    
    if memory.context.count() < 20:
        memory.context.add(message)

def get_memory_context(user: str) -> str:
    """
    Retrieve the combined text of the user's memory messages.

    Args:
        user (str): The username of the user.

    Returns:
        str: Consolidated memory text, or "Nothing" if empty.

    document by AI
    """
    memory = Memory.objects.filter(user__username=user).first()

    if not memory:
        return "Nothing"
    
    messages = memory.context.all()
    if not messages:
        return "Nothing"
    
    context_text = "\n".join(message.text for message in messages)
    
    return context_text

def create_new_message(chat_uuid: Union[uuid.UUID, str], is_ai: bool, text: str) -> Optional[Message]:
    """
    Create a new message in a chat and append it to user memory.

    Args:
        chat_uuid (Union[uuid.UUID, str]): The UUID of the chat session.
        is_ai (bool): True if the message is generated by AI.
        text (str): The text content of the message.

    Returns:
        Optional[Message]: The created Message instance, or None if chat not found.

    document by AI
    """
    try:
        chat = Chat.objects.get(uuid=chat_uuid)
        new_message = Message.objects.create(text=text, is_ai=is_ai, chat=chat)
        add_to_memory(chat.user , new_message)
        return new_message
    except Chat.DoesNotExist:
        return None

def delete_chat_by_uuid(user_username: str, uuid: Union[uuid.UUID, str]) -> None:
    """
    Delete a chat session by its UUID and owner username.

    Args:
        user_username (str): The username of the chat owner.
        uuid (Union[uuid.UUID, str]): The UUID of the chat to delete.

    document by AI
    """
    Chat.objects.filter(uuid=uuid, user__username=user_username).delete()

def get_chat_messages(uuid: Union[uuid.UUID, str]) -> List[Message]:
    """
    Retrieve the last 20 messages of a chat session, in chronological order.

    Args:
        uuid (Union[uuid.UUID, str]): The UUID of the chat session.

    Returns:
        List[Message]: Chronological list of Message objects.

    document by AI
    """
    try:
        chat = Chat.objects.get(uuid=uuid)
        latest_messages = chat.context.all().order_by('-id')[:20]
        
        return list(reversed(latest_messages))
    except Chat.DoesNotExist:
        return []